# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
#theme: jekyll-theme-tactile
plugins:
  - jekyll-sitemap
navbar-links:
  About Me: "aboutme"
  Resources:
    - Test1: "Konzept"
    - Test2: "Konzept.md"
  Author's home: "http://thomas-ramm.de"
